---
- name: Add Official Nginx Repository
  apt_repository: repo="deb http://nginx.org/packages/ubuntu/ trusty nginx" update_cache=yes

- name: Add Nginx apt-key
  apt_key: url="http://nginx.org/keys/nginx_signing.key" state=present

- name: update apt (again)
  command: apt-get update

- name: Install Nginx
  apt: name=nginx state=present force=yes

- name: Create nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Disable Nginx from starting on boot
  service: name=nginx enabled=no state=stopped

- name: Disable default site
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Disable default SSL site
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent

- name: Create HHVM site configuration
  template: src=hhvm.conf.j2 dest=/etc/nginx/conf.d/hhvm.conf

- name: Start Nginx Server
  service: name=nginx state=started
  when: nginx is defined
