---
- name: Add Nginx PPA
  apt_repository: repo="deb http://ppa.launchpad.net/nginx/development/ubuntu trusty main" update_cache=yes

- name: Add Nginx apt-key
  apt_key: url="http://nginx.org/keys/nginx_signing.key" state=present

- name: Install Nginx
  apt: name=nginx state=present force=yes

- name: Create nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Disable Nginx from starting on boot
  service: name=nginx enabled=no state=stopped

- name: Disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create HHVM site configuration
  template: src=hhvm.conf.j2 dest=/etc/nginx/sites-available/hhvm.conf

- name: Enable HHVM site configuration
  file: src="/etc/nginx/sites-available/hhvm.conf"
        dest="/etc/nginx/sites-enabled/hhvm.conf"
        owner=root
        group=root
        state=link

- name: Start Nginx Server
  service: name=nginx state=started
  when: nginx is defined
